DROP TABLE IF EXISTS AB_CUSTOMERS;

DROP TABLE IF EXISTS AB_ORDERS;

DROP TABLE IF EXISTS AB_PRODUCTS;

DROP TABLE IF EXISTS AB_TIME;

DROP TABLE IF EXISTS AB_CATEGORIES;

DROP TABLE IF EXISTS AB_ORDERDETAILS;