-- TABLE CREATION SCRIPT

CREATE TABLE "AB_CUSTOMERS" ("CUSTOMERID" NUMBER, "CUSTOMERNAME" TEXT, "CONTACTNAME" TEXT, "ADDRESS" TEXT, "CITY" TEXT, "POSTALCODE" TEXT, "COUNTRY" TEXT, PRIMARY KEY ("CUSTOMERID"));

CREATE TABLE "AB_ORDERS" ("ORDERID" NUMBER, "CUSTOMERID" NUMBER, "EMPLOYEEID" NUMBER, "ORDERYEAR" NUMBER, "ORDERMONTH" NUMBER,"ORDERDAY" NUMBER, "SHIPPERID" NUMBER, PRIMARY KEY ("ORDERID"));

CREATE TABLE "AB_PRODUCTS" ("PRODUCTID" NUMBER, "PRODUCTNAME" TEXT, "SUPPLIERID" NUMBER, "CATEGORYID" NUMBER, "UNIT" TEXT, "PRICE" NUMBER, PRIMARY KEY ("PRODUCTID"));

CREATE TABLE "AB_TIME" ( "ROW_IDENTIFIER" VARCHAR2(500), "TIME_LEVEL" VARCHAR2(500), "END_YEAR" NUMBER, "END_MONTH" NUMBER, "END_DAY" NUMBER, "TIME_SPAN_IN_DAYS" NUMBER);
  
CREATE TABLE "AB_CATEGORIES" ("CATEGORYID" NUMBER, "CATEGORYNAME" TEXT, "DESCRIPTION" TEXT, PRIMARY KEY ("CATEGORYID"));
  
CREATE TABLE "AB_ORDERDETAILS" ("ORDERDETAILID" NUMBER, "ORDERID" NUMBER, "PRODUCTID" NUMBER, "QUANTITY" NUMBER);